import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="bg-gray-100">
          <div className="px-8 md:px-16 lg:px-32">
              <div className="grid grid-cols-12 pt-8">
                  <header className="col-span-4">
                      <div>
                          <a href="index.html">
                              <h1 className="text-4xl">Agency</h1>
                          </a>
                      </div>
                  </header>
                  <div className="col-span-7 md:hidden"></div>
                  <div id="burger" className="col-span-1 cursor-pointer md:hidden">
                      <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                          xmlns="http://www.w3.org/2000/svg">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M4 6h16M4 12h16M4 18h16">
                          </path>
                      </svg>
                  </div>
                  <nav id="menu" className="col-span-12 lg:col-span-8 my-3 hidden md:block">
                      <ul className="md:grid md:grid-cols-2">
                          <div className="md:flex md:justify-between">
                              <li className="my-2 md:inline md:my-0"><a href="#">Services</a></li>
                              <li className="my-2 md:inline md:my-0"><a href="#">About Us</a></li>
                              <li className="my-2 md:inline md:my-0"><a href="#">Contact</a></li>
                          </div>
                          <div className="md:flex md:justify-end">
                              <li className="my-2 md:inline md:my-0">
                                  <a href="#" className="md:px-4 md:py-2 md:rounded-md md:bg-gray-500 md:text-white">Get in touch</a>
                              </li>
                          </div>
                      </ul>
                  </nav>
              </div>
              <div className="my-4">
                  <div className="grid grid-cols-4">
                      <div className="pr-6 py-8 md:py-16 col-span-4 md:col-span-2 ">
                          <h2 className="text-4xl md:text-6xl font-semibold tracking-wide leading-normal text-primary">
                            GET SECURED & PROTECTED                            
                          </h2>
                          <p className="py-6 text-xl leading-normal">
                            At Black Tiger we got you covered. We have a high expertise in Physical security, Protective Security, Trained Patrol Dogs, Access Control & Equipment, Protocol Services...
                          </p>
                          <div className="py-4 lg:py-0">
                              <a href="#" className="bg-gray-500 text-white rounded-md px-9 py-4 font-semibold">
                                  <svg className="w-6 h-6 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                                      xmlns="http://www.w3.org/2000/svg">
                                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z">
                                      </path>
                                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                  </svg>
                                  Watch Video
                              </a>
                          </div>
                      </div>
                      <div className="px-3 col-span-4 order-first md:col-span-2 md:order-1 lg:col-span-1">
                          <Image src="/hero1.svg" alt="Black Tiger's Security" width={50} height={112} className="h-112 mt-5 w-full object-cover rounded-tl-big rounded-br-big"/>
                      </div>
                      <div className="pl-3 hidden order-2 lg:block">
                          <img src="images/man.jpg" alt="image 2"
                              className="h-60 w-full mb-3 object-cover rounded-tl-big rounded-br-big"/>
                          <img src="images/comp.jpg" alt="image 3"
                              className="h-60 w-full mt-3 object-cover rounded-tl-big rounded-br-big"/>
                      </div>
                  </div>
              </div>
          </div>
        </div>        
        
      </main>


    </div>
  )
}
